# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNBaseProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNBaseProject

  # pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  # pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'RNBaseProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
