# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tutorApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tutorApp

  # pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  # pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'

  # pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  
  # Add these to fix react-native duplicate error.
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end
